server:
  port: 10152

spring:
  application:
    name: TestPTMK
  datasource:
    url: jdbc:postgresql://localhost:5432/test_SkillRocks
    username: postgres
    password: 1901magic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
